### ISSUE TITLE
GTWVT: SetMode() freezes app in MT

### ISSUE THREAD

**Issue by nchristophi** [harbour/core#115]
In MT application and using GTWVT executing SETMODE in child thread the application freezes. If i use GTWIN it works fine.
See the following code

``` harbour
REQUEST HB_GT_WVT_DEFAULT
REQUEST HB_GT_WIN
REQUEST HB_GT_WVG

PROCEDURE Main()
   LOCAL i
   hb_threadStart( @mythread() )
   CLS
   FOR i := 1 TO 100000
      hb_DispOutAt( 5, 5, i )
   NEXT
   RETURN

PROCEDURE myThread()
   SetMode( 30, 96 )
   DO WHILE .T.
      hb_DispOutAt( 10, 10, hb_DateTime() )
      hb_idleSleep( 1 )
   ENDDO
   RETURN
```

Best regards
Nikos

**Comment by JoseQuintas** [comment]
It is not a bug, it is a invalid use of multithread/hb_idlesleep() freezing main window.

```
FUNCTION myThread()
hb_gtReLoad( "WVT" ) // <<---- with this do not freeze
do while .t.
  hb_dispoutat(10,10,date())
  hb_idlesleep(1)
enddo
```
Ask on harbour-users about a better way to show date/time.

**Comment by alcz** [comment]
One principal of Windows Win32 programming is that a single window event loop and all actions regarding its GDI objects should be managed by single thread. The additional question is if GTWVT can do something to at least prevent freezing. Either RTE on wrong thread or forward calls to thread that created window?

GTWIN works - because Win32 console API is different
GTWVT - only separate window per thread or using sth like```hb_mutexNotify( pMutex, { || hb_DispOut(...) } )``` in specific cases

If we leave it as Win32 limitation, then this issue should be closed.

**Comment by JoseQuintas** [comment]
If Main Window do the work, you can not sleep it.
Now, it does not freeze.

```
REQUEST HB_GT_WVT_DEFAULT

PROCEDURE Main()
   LOCAL i
   CLS
   hb_threadStart( @mythread() )
   FOR i := 1 TO 100000
      hb_DispOutAt( 5, 5, i )
   NEXT
   RETURN

PROCEDURE myThread()
   SetMode( 30, 96 )
   DO WHILE .T.
      hb_DispOutAt( 10, 10, hb_DateTime() )
      Inkey(1)
   ENDDO
   RETURN
```

**Comment by alcz** [comment]
Yes, that's because Inkey() in GTWVT processes Windows GDI messages. 
It's different than in GTWIN.
According to Windows programming guidelines only one thread should be 
accessing one window,
otherwise you can encounter unpredictable results, not only freezes, 
also memory corruption.

Your example freezes here...

hb_gtLock() hb_gtUnlock() may help to create somewhat safer code... but 
even that fails. So i see the only rule with Windows: 1 window -> 1 thread.

|REQUEST HB_GT_WVT_DEFAULT

PROCEDURE Main()
   LOCAL i
   CLS
   hb_threadStart( @mythread() )
   FOR i := 1 TO 100000
      hb_gtLock()
      hb_DispOutAt( 5, 5, i )
      Inkey()
      hb_gtUnlock()
   NEXT
   RETURN

PROCEDURE myThread()
   hb_gtLock()
   SetMode( 30, 96 )
   hb_gtUnlock()
   DO WHILE .T.
      hb_gtLock()
      hb_DispOutAt( 10, 10, hb_DateTime() )
      hb_gtUnlock()
      hb_idleSleep(1)
   ENDDO
   RETURN|


The only working example is:

REQUEST HB_GT_WVT_DEFAULT

STATIC m

PROCEDURE Main()

    LOCAL i, bBlock

    m := hb_MutexCreate()

    CLS

    hb_threadStart( @mythread() )

    FOR i := 1 TO 100000

       IF hb_mutexSubscribe( m, 0, @bBlock )
          Eval( bBlock )
       ENDIF

       hb_DispOutAt( 5, 5, i )

    NEXT

    RETURN

PROCEDURE myThread()

    hb_MutexNotify( m, { || SetMode( 30, 96 ) } )

    DO WHILE .T.

       hb_MutexNotify( m, { || hb_DispOutAt( 10, 10, hb_DateTime() ) } )
       hb_IdleSleep(1)

    ENDDO

    RETURN

Is probably an idea of sub-GT that would automatically serialize all 
screen calls like that.

Best regards, Aleksander Czajczynski

José M. C. Quintas wrote:

**Comment by JoseQuintas** [comment]
Why not this:

```
PROCEDURE Main()
   LOCAL i
   hb_threadStart( @mythread() )
   SetMode( 30, 96 )
   CLS
   FOR i := 1 TO 100000
      hb_DispOutAt( 5, 5, i )
   NEXT
   RETURN

PROCEDURE myThread()
   DO WHILE .T.
      hb_DispOutAt( 10, 10, hb_DateTime() )
      Inkey(1)
   ENDDO
   RETURN

PROCEDURE HB_GTSYS
   REQUEST HB_GT_WVT_DEFAULT
   RETURN
```

**Comment by alcz** [comment]
[i've rewritten previous e-mail reply, because it looked really poor, and there was no reasonable way to edit it]

Yes, that's because Inkey() in GTWVT processes Windows GDI messages. 
It's different than in GTWIN. According to Windows programming guidelines only one thread should be 
accessing one window, otherwise you can encounter unpredictable results, not only freezes, 
also memory corruption.

Your [**1**] example freezes here...

hb_gtLock() hb_gtUnlock() may help to create somewhat safer code... but 
even that fails. So i see the only rule with Windows: 1 window -> 1 thread.

```harbour
REQUEST HB_GT_WVT_DEFAULT

PROCEDURE Main()
   LOCAL i
   CLS
   hb_threadStart( @mythread() )
   FOR i := 1 TO 100000
      hb_gtLock()
      hb_DispOutAt( 5, 5, i )
      Inkey()
      hb_gtUnlock()
   NEXT
   RETURN

PROCEDURE myThread()
   hb_gtLock()
   SetMode( 30, 96 )
   hb_gtUnlock()
   DO WHILE .T.
      hb_gtLock()
      hb_DispOutAt( 10, 10, hb_DateTime() )
      hb_gtUnlock()
      hb_idleSleep(1)
   ENDDO
   RETURN
```

**The only working example is:**

```harbour
REQUEST HB_GT_WVT_DEFAULT

STATIC m

PROCEDURE Main()
    LOCAL i, bBlock
    m := hb_MutexCreate()
    CLS
    hb_threadStart( @mythread() )
    FOR i := 1 TO 100000
       IF hb_mutexSubscribe( m, 0, @bBlock )
          Eval( bBlock )
       ENDIF
       hb_DispOutAt( 5, 5, i )
    NEXT
    RETURN

PROCEDURE myThread()
    hb_MutexNotify( m, { || SetMode( 30, 96 ) } )
    DO WHILE .T.
       hb_MutexNotify( m, { || hb_DispOutAt( 10, 10, hb_DateTime() ) } )
       hb_IdleSleep(1)
    ENDDO

    RETURN
```

Is probably an idea of sub-GT that would automatically serialize all 
screen calls like that.

Your example [**2**] with SetMode() moved to first thread. Here any undefined behaviour doesn't show up, there is no freeze, but there is still no guarantee that something will be not screwed in larger program. 

Best regards, Aleksander Czajczynski
