### ISSUE TITLE
Some warnings with msvc 2013 64 bits

### ISSUE THREAD

**Issue by Rossine** [harbour/core#125]
Hi Viktor,

I see this warnings with msvc 2013 64 bits:

```
cl.exe -nologo -c -O2  -DHBMK_HAS_OPENSSL -DHB_OPENSSL_STATIC -TP -W4 -wd4127 -DUNICODE -Fo..\lib\wi
n\msvc64\.hbmk\hbssls\ -I..\include -I"c:\devout\openssl-1.0.2d\include" ..\lib\win\msvc64\.hbmk\hbs
sls\ssl_hbco.c ..\lib\win\msvc64\.hbmk\hbssls\hbssl.c hbssl\ssl_hb.c hbssl\ssl_inet.c hbssl\ssl_sock
.c hbssl\bio.c hbssl\err.c hbssl\evp.c hbssl\evpciph.c hbssl\evpenc.c hbssl\evpmd.c hbssl\evppkey.c
hbssl\pem.c hbssl\rand.c hbssl\ssl.c hbssl\sslciph.c hbssl\sslctx.c hbssl\sslsess.c hbssl\x509.c
ssl_hbco.c
hbssl.c
ssl_hb.c
ssl_inet.c
ssl_sock.c
hbssl\ssl_sock.c(285) : warning C4244: 'argument' : conversion from 'HB_SOCKET' to 'int', possible loss of data
bio.c
err.c
evp.c
evpciph.c
evpenc.c
evpmd.c
evppkey.c
pem.c
rand.c
ssl.c
sslciph.c
sslctx.c
sslsess.c
x509.c
Generating Code...
hbmk2: Creating static library... ..\lib\win\msvc64\hbssls.lib



...




cl.exe -nologo -c -O2  -DHAVE_CONFIG_H -DHBMK_HAS_ED25519 -DHBMK_HAS_SCRYPT -TP -W4 -wd4127 -DUNICOD
E -Fo..\lib\win\msvc64\.hbmk\hbcrypto\ -I..\include -Ihbcrypto\3rd\ed25519 -Ihbcrypto\3rd\scrypt ..\
lib\win\msvc64\.hbmk\hbcrypto\scryptcf.c ..\lib\win\msvc64\.hbmk\hbcrypto\hbcrypto.c hbcrypto\aes256
.c hbcrypto\bcrypt.c hbcrypto\blake2b.c hbcrypto\blake2s.c hbcrypto\ed25519.c hbcrypto\sha3.c hbcryp
to\pbkdf2.c hbcrypto\scrypt.c hbcrypto\strcmpc.c
scryptcf.c
hbcrypto.c
aes256.c
bcrypt.c
blake2b.c
blake2s.c
ed25519.c
sha3.c
hbcrypto\sha3.c(285) : warning C4244: '=' : conversion from 'HB_SIZE' to 'unsigned int', possible loss of data
hbcrypto\sha3.c(312) : warning C4244: '=' : conversion from 'HB_SIZE' to 'unsigned int', possible loss of data
hbcrypto\sha3.c(366) : warning C4244: 'argument' : conversion from 'HB_SIZE' to 'int', possible loss of data
hbcrypto\sha3.c(388) : warning C4244: 'argument' : conversion from 'HB_SIZE' to 'int', possible loss of data
pbkdf2.c
scrypt.c
strcmpc.c
Generating Code...
hbmk2: Creating static library... ..\lib\win\msvc64\hbcrypto.lib
```

Regards,

Rossine.

**Comment by vszakats** [comment]
Please don't send 3.4 reports here or other mainline (3.2) forums. For more, see my note here:
https://github.com/vszakats/harbour-core/commit/38644a39cf22275d7bb5b675eda7d33a19fcd77c#diff-92d0e5376f9e604e03fac86fbb661950R18

Even though the first warning applies to 3.2 too, so I'm leaving this open.

**Comment by Rossine** [comment]
Sorry Viktor, 

I try post in harbour 3.4 and I post in harbour 3.2. 

I'll try again post harbour 3.4

Sorry my fault :(

**Comment by vszakats** [comment]
After further reading about it the upstream problem is really an OpenSSL API issue, which should be fixed there. Or it can be silenced in an ugly way locally.

**Comment by Rossine** [comment]
Hi Viktor,

I not see the folder "Questions" no more exists.

When I click Pull Request a message is posted in harbor 3.2

How to I post errors / doubts in harbour 3.4 ?

Regards,

Rossine.

**Comment by vszakats** [comment]
There was never was a "Questions" tab (though it should at this moment '404', and neither redirect you here, nor to the PR tab automatically). I've made an experiment to open the "Issues" tab, but it often slipped into a support/question forum, which I just have no capacity to maintain at this time (each of those - even the "invalid" ones - require a substantial amount of free-time investment to handle). As I wrote, please be proactive and do as much investigation as possible and try to address issues with patch submissions (via Pull Requests), or try escalating it to upstream 3.2 if the problem is present there, or escalating it to 3rd party code (in this case the other part of the issue, or broadly speaking both parts). Or use tooling/components which happen to be in the mainline of development. Besides these, I'm trying to reciprocate support to donators privately, besides the general tasks of maintaining this fork. All this might change in the future, but thus far I'm still spreading too thin while running Harbour on a shoestring.

**Comment by Rossine** [comment]
OK Viktor, many thanks.

Rossine.
