### ISSUE TITLE
Warning W0032  Variable 'NFOR' is assigned but not used in function 'MAIN(8)'

### ISSUE THREAD

**Issue by NaldoDj** [harbour/core#135]
function Main()
    local nFor   as numeric
    local nTmp	 as numeric
    local nStep  as numeric
    local nTotal as numeric
    nStep:=5
    nTotal:=1000
    for nFor:=1 to nTotal step nStep
	? HB_RandomInt(nTmp++,nTotal)
    next nFor
    return(0)

D:\tmp\hb>c:\GitHub\core\bin\win\mingw\hbmk2 forWarning.prg
hbmk2: Processando script local: hbmk.hbm
Harbour 3.2.0dev (r1611161510)
Copyright (c) 1999-2016, http://harbour-project.org/
Compiling 'forWarning.prg'...
forWarning.prg(12) Warning W0032  Variable 'NFOR' is assigned but not used in function 'MAIN(8)'

No code generated.
hbmk2: Erro: Executando o compilador Harbour (interno): 1
(c:\GitHub\core\bin\win\mingw\harbour.exe) -n2 forWarning.prg -w3 -es2 -oC:\Users\marin\AppData\Local\Temp\hbmk_cjfzxx.dir\ -ic:\GitHub\core\include -undef:.ARCH. -D__PLATFORM__WINDOWS -D__LITTLE_ENDIAN__ -D__ARCH64BIT__

**Comment by mlacecilia** [comment]
Hi, maybe declaring 'as numeric' preassigns a numerical value (probably 0)
to the variable.
This triggers the warning when the for reassigns the variable.
JM2C
Best regards.
--
Maurizio

Il 11/dic/2016 20:26, "Naldo DJ" <notifications@github.com> ha scritto:

**Comment by mlacecilia** [comment]
Sorry, my previous suggestion is wrong.
Same should happen for nStep and nTotal variables.
Something of strange or buggy is happening.
Please, try to compile this code, acting the same thing of your :

function Main()
local nFor as numeric
local nTmp as numeric
local nTotal as numeric
nTotal:=1000
for nFor := 1 to nTotal step 5
? HB_RandomInt(nTmp++,nTotal)
next nFor
return(0)

On my side it compile fine.
I'm asking some guru opinion about this side effect of STEP clause.

Anyway, your code is wrong because you're incrementing nTmp before to 
assign a numerical value to it and an error is issued running the 
executable.
Best regards.
--
Maurizio



Il 11/12/2016 20:37, Maurizio la Cecilia ha scritto:

**Comment by vszakats** [comment]
https://groups.google.com/d/msg/harbour-devel/9w3qcPvQonw/G_ELmTY0BAAJ

**Comment by alcz** [comment]
Test code supplied compiles without warnings (-w3) after  50083715672297e0da7e3cee47f8fb767b7d200e thanks to @druzus. This issue can be closed.

Original test code has RTE behaviour on incrementing NIL, it runs after changing
```harbour
local nTmp as numeric
```
to
```harbour
local nTmp as numeric := 1
```

I think it's not the syntax i'd expect, should it be the other way?
 ```harbour
local nTmp := 1 as numeric
```
