### ISSUE TITLE
Linux WSL (Ubuntu 14.04.5 LTS): undefined reference to symbol 'log10@@GLIBC_2.2.5'

### ISSUE THREAD

**Issue by dmajkic** [harbour/core#146]
I am receiving this message when including hbct in hbmk project:

> /usr/bin/ld: ...libhbct.a(ctmath2.o): undefined reference to symbol 'log10@@GLIBC_2.2.5'
> /..../x86_64-linux-gnu/libm.so: error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status
> 
> hbmk2[hbmk]: Error: Running linker. 1
> gcc .hbmk/app.o .hbmk/tgetlist.o '.hbmk/_hbmkaut_app.o'   -Wl,--start-group -lgtsln -lhbct -lhbmzip -lminizip -lhbmisc -lhbmemio -lhbziparc -lhbnf -lhbssl -lssl -lcrypto -lhbtip -lxhb -lhbfship -lhbxpp -lSYS -lUI  -lhbcplr -lhbdebug -lslang -lharbour   -lm -Wl,--end-group -oApp -L/usr/local/lib/harbour -Lsys
> 

Math module is linked via _-ldflag+=-lm_, and _-lm_ can be seen just before _--end-group_. Yet I am still receving the same error. 

Any hints?

**Comment by vszakats** [comment]
The same issue was fixed in this (3.4) commit: https://github.com/vszakats/harbour-core/commit/53560d75b099b167bbe1d4520185ac09b6350b75

**Comment by df7be** [comment]
Hello dmajkic,
I had this problem too and it was solved a long time ago.
See the references below.
The solution is, that the list of the system libs must be at the end of the linking command for your own Harbour Application, see the sample lines:

export SYSTEM_LIBS="-lm -lpcre"

$HRB_BIN/harbour $PGM_NAME -n -i$HRB_INC -i$HWGUI_INC -w0 -d__LINUX__ $2
gcc $PGM_NAME.c -o$PGM_NAME -I $HRB_INC -L $HRB_LIB -L $HWGUI_LIB -Wl,--start-group $HWGUI_LIBS $HARBOUR_LIBS -Wl,--end-group `pkg-config --cflags gtk+-2.0` `pkg-config gtk+-2.0 --libs` $SYSTEM_LIBS
...

If you have no external (C-)modules, the best way is to create the exe-file  with the hbmk2 command.
With the lines
SET PROCEDURE TO ...
all dependencies are included and you need no Makefile. Look into
https://sourceforge.net/p/cllog/code/HEAD/tree/trunk/src/log.prg
about line 156:
#include "logmodhb.ch"
Here are the procedures listed:
https://sourceforge.net/p/cllog/code/HEAD/tree/trunk/src/logmodhb.ch
SET PROCEDURE TO s87      && <S87> Funktionen aus Clipper 5
SET PROCEDURE TO windows  && DBFAST: Windows-Elemente  (alle)
SET PROCEDURE TO logopen  && Oeffnen und indizieren    (alle)
SET PROCEDURE TO codepage && Umlaute Plattform abhaengig
...
You could write the lines also directly in to the code of your main module 

In HWGUI, this bug was closed
https://sourceforge.net/p/hwgui/bugs/4/

Here is for example the script building my App for HWGUI "logw.prg": 
https://sourceforge.net/p/cllog/code/HEAD/tree/trunk/src/hwmk.sh

I hope, this helps you.
I think, if you have checked this, please give a feedback to the Harbour team,
if this issue is ready for close.

My App with Harbour as a Terminal App and with HWGUI as a X11-app
can successfully build under following 3 OS'es:
Ubuntu 16.04 TLS
Ubuntu 18.04 TLS
MintLINUX 19.2 Cinnamon

With best regards,
73 es 55 de
DF7BE Wilfried

**Comment by dmajkic** [comment]
@df7be thank you!
