### ISSUE TITLE
Delivering translation of error messages to german (FRG and Austria)

### ISSUE THREAD

**Issue by df7be** [harbour/core#203]
Hello Aleksander,
in the appended ZIP-file you find the files l_de.c and l_de_at.c for
commit into directory src/lang.
Referred to #201 (IBM Codepage DE858) i'll
[hblangde.zip](https://github.com/harbour/core/files/4184559/hblangde.zip)
 test this translation together with this issue.
I've done a quick test with an bound error of an array (index exeeds the number of elements).
MNI TNX and
With regards
DF7BE Wilfried

**Comment by alcz** [comment]
Thank you for this contribution. I've asked someone else, who is german speaking, to take a look at those messages, if he can understand all of them - now i'm waiting for the response.
For me they are very hard to read obviously!

There was minor technical correction, one string format token was: &s instead of %s

**Comment by alcz** [comment]
As submitted by df7be being evaluated in my repo:
https://github.com/alcz/harbour/commit/a6639105267d0dbdd0d81f0777a218ce4ab36cd0

After a review by Jan Fornoff:
https://github.com/alcz/harbour/pull/1/files#diff-44382137d1abef4b69d8b5a46d132645

Seems good. One last doubt is if we really should use german for strictly technical terms like:  stack, lock, string, pointer or translate them back. English vocabulary here can be more direct and meaningful here, even for native german speakers. I had the same thoughts originally, Jan wrote about that too.

Anyone?

Before commiting to core repo i'll strip all the english comments from the file.

**Comment by df7be** [comment]
Hello Aleksander,
the modifications of Jan are okay !

My mission is to avoid "Denglish" in the usage of language.
So i use the strict translation of technical expressions.
(e.g. Stack ==> Stapelspeicher, String ==> Zeichenkette)
Bad example for Denglish: "Body bag", is a bag for a dead person (Leichensack), in Denglish it is a bag carrying things at the body. Many people outside germany are confused about the use of this expression.

I worked a long time in the information technology (since 1979) and i have read all the
manuals in german of the OS "BS2000".

I suggest before the issue is pulled:
not to remove the comments with the original english text.
I'm a friend of a many inline commment, it helps me and
other programmers after several decades (CLLOG exists since 1995) to modify the code to new requirements.
Remove them in the copy to the austrian file, beacuse the it is possible to reference the german file.
I think about later issues of harbour, it could be possible, that the position in the array could be changed.
For non german programmers it is easier to set the message quite correct to the new position.

You can close the issue.

Many thanks es 73 and 55
With reagards
DF7BE, Wilfried

**Comment by alcz** [comment]
Hi Wilfried!
Your changes are now commited to the master repository.
https://github.com/harbour/core/commit/cfd6201fa9e33253d3a43741b48612d07c2fa2ef

I've removed the comments here, because it's the standard set by other translations. I'm not going to judge the way it is, nor i want to change it.

Original formatting of your submission will be kept in my repo for reference:
https://github.com/alcz/harbour/blob/ef942d0bbd15c2e85f62dd5661d34ae4b81a1c3e/src/lang/l_de.c

Best regards, AC

**Comment by df7be** [comment]
Hello Aleksander,
MNI TNX. I'll use the new Harbour code snapshot in the next Issue of my app "CLLOG".
In the past, i tested some Clipper compatible compilers, but Harbour is the best one !!!
I close the issue.

Best regards de
DF7BE, Wilfried
