### ISSUE TITLE
hbmk2: Error: Running C/C++ compiler

### ISSUE THREAD

**Issue by RBTCHENTPE** [harbour/core#256]
WIN 10 WITH HARBOUR COMPILE PROBLEMS Error: running C/C++ compile
1. already install C++compile
2. already set path in my computer.  C:\BCC102\bin 
    “This PC” System variable already Add new path to c:\BCC102\bin”in good order 

Hopefully, an expert will help to solve the problems. 

C:\hb32\bin>set path=c:\hb32\bin;c:\hb32\lib\win\mingw

C:\hb32\bin>hbmk2 c:/hb32/tests/hello.prg -comp=mingw64
Harbour 3.2.0dev (r2104281802)
Copyright (c) 1999-2021, https://harbour.github.io/
Compiling 'c:\hb32\tests\hello.prg'...
Lines 4, Functions/Procedures 1
Generating C source output to 'C:\Users\rbtch\AppData\Local\Temp\hbmk_aw8t35.dir\hello.c'... Done.
hbmk2: Error: Running C/C++ compiler. -1
gcc.exe -c -O3  -W -Wall -pipe -IC:/hb32/include C:/Users/rbtch/AppData/Local/Temp/hbmk_aw8t35.dir/hello.c C:/Users/rbtch/AppData/Local/Temp/hbmk_lmb9ac.c

remark:
'c:\hb32\tests\hello.prg' contents as follows:

// Typical welcome message
PROCEDURE Main()
   ? "Hello, world!"
RETURN

Thanks,
Robert Chen

**Comment by Petewg** [comment]
Hi
here's the absolutely wrong place, for reporting this kind of "problems". 
your problem is merely an improper mixture of BCC10.2 C compiler and MinGW Harbour binaries, which is not going to work.
please, move your post to [harbour-users group](https://groups.google.com/g/harbour-users) and be sure you will get detailed instructions on how to resolve it.
