### ISSUE TITLE
hbmk2 not expands wildcards in file name

### ISSUE THREAD

**Issue by fsgiudice** [harbour/core#95]
Hi Viktor,
I'm trying to use:
hbmk2 scripts\*.hbs
result is:
```
hbmk2: Elaborazione in corso delle opzioni d'ambiente: -comp=mingw
Harbour 3.2.0dev (r1503052135)
Copyright (c) 1999-2015, http://harbour-project.org/
Cannot open scripts\*.hbs, assumed external

No code generated.
hbmk2: Error: Running Harbour compiler (embedded). 1
(j:\git\harbour_qt\bin\harbour.exe) -n2 scripts\*.hbs -oC:\Users\FSG\AppData\Local\Temp\hbmk_qkpp1g.dir\ -ij:\git\harbour_qt\include
```
looking at hbmk2 sources it seems to handle only explicit extensions, i.e. *.prg works.
Is there a way to handle it ?
BR
Francesco

**Comment by vszakats** [comment]
Hi Francesco, `hbmk2` would only expand _known_ extensions, f.e. `.prg` and `.hb`. The problem here is `.hbs` was once a known extension but it got changed to `.hb` about 3 years ago (b57f2526a79cc43cffea1d8747546e9e10551d40 f5390e31ff6dae43f49b235ee656cda8077cb234) and `.hbs` deprecated.
As a solution I suggest to use the new one - `.hb` - and it will be expanded. As for expanding unknown file-types, there are some potential unwanted effects and corner cases there, I'm not sure I'd feel comfortable to implement it.

**Comment by fsgiudice** [comment]
Hi Viktor,
thank you for your reply. Files updated to .hb extension and now it works.
